name: Webshop
favicon: null
layout_spectrum: 0.1859320318326354
typography_spectrum: 0.6677921935915947
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.49891971168108284
  lightness: 0.8896986115723848
  saturation: 0.5214824816212058
  rhythmicContrast: 0.05323614040389657
purpose: []
